### ISSUE TITLE
How to store .torrent file (without configuring transmission)?

### ISSUE THREAD

**Issue by a-t-0** [usma0118/magnet2torrent#36]
Hi, thank you for your work, and nice to see you using pre-commits! After creating the environment, and specifying the magnet and torrent watch folders with:
```
export magnet_watch=/some/dir
export torrent_blackhole=/some/other_dir
```
I was trying to convert a magnet link into a `.torrent` file using:
```
python main.py -m some_magnet_link
```
And I got the error that the transmission_host was not found. It seems like the software tries to pass the magnet link into transmission, instead of downloading a `.torrent` file. Would you be able to explain:

0. Whether it is possible to directly convert a magnet link to a `.torrent` file with this repository?
1. What the output folder of this `.torrent` file would be?

**Comment by usma0118** [comment]
The CLI part of the application requires a bit of rework. 

You can run an application in daemon mode (monitor mode, no param) that would monitor watch folder for any new files created as *.magnet and convert them to .torrent.

Otherwise you can run 
`python main.py -m some_magnet_link`
that would covert provided link and place it in output direct (env variable).

`python main.py -m some_magnet_link -o outputfolder`

will output in sepcified folder.
